final List<Map<String, Object>> product = [
  {
    "id": 0,
    "title": "Men's Nike Shoes",
    "brand": "Nike",
    "size": [7, 8, 9, 10],
    "price": 44.52,
    "imageurl": "assets/images/shoes_1.png",
  },
  {
    "id": 01,
    "title": "Women's Adidas Shoes",
    "brand": "Adidas",
    "size": [7, 8, 9],
    "price": 36.78,
    "imageurl": "assets/images/shoes_2.png",
  },
  {
    "id": 02,
    "title": "Bata shoes",
    "brand": "Bata",
    "size": [7, 8, 10],
    "price": 29.52,
    "imageurl": "assets/images/shoes_3.png",
  },
  {
    "id": 03,
    "title": "Kids Shoes",
    "brand": "Service",
    "size": [8],
    "price": 40.52,
    "imageurl": "assets/images/shoes_4.png",
  },
  {
    "id": 04,
    "title": "Women's Gucci Shoes",
    "brand": "Gucci",
    "size": [6, 7, 9],
    "price": 53.55,
    "imageurl": "assets/images/g1.png",
  },
  {
    "id": 05,
    "title": "Kidos Shoes",
    "brand": "Nike",
    "size": [4, 6, 8],
    "price": 33.69,
    "imageurl": "assets/images/n2.png",
  },
  {
    "id": 06,
    "title": "Men Shoes",
    "brand": "Bata",
    "size": [8, 9, 10],
    "price": 60.52,
    "imageurl": "assets/images/b2.png",
  },
  {
    "id": 07,
    "title": "Nike Shoes",
    "brand": "Nike",
    "size": [6, 7, 8, 9, 10],
    "price": 40.45,
    "imageurl": "assets/images/n1.png",
  },
  {
    "id": 08,
    "title": "Jogging Shoes",
    "brand": "Adidas",
    "size": [6, 7, 8, 9, 10],
    "price": 63.45,
    "imageurl": "assets/images/a1.png",
  },
];
